// ── ALL QUESTS ────────────────────────────────────────────────────────────────
export const ALL_QUESTS = [
  // Revised Core Set
  { id:'ptm',  name:'Passage Through Mirkwood',        cycle:'Revised Core Set',              diff:2.2 },
  { id:'jata', name:'Journey Along the Anduin',         cycle:'Revised Core Set',              diff:5.3 },
  { id:'efdg', name:'Escape from Dol Guldur',           cycle:'Revised Core Set',              diff:7.8 },
  // Dark of Mirkwood (campaign only)
  { id:'oath', name:'The Oath',                         cycle:'Dark of Mirkwood',              diff:2.3, campaignOnly:true },
  { id:'cnd',  name:'The Caves of Nibin-Dûm',          cycle:'Dark of Mirkwood',              diff:4.7, campaignOnly:true },
  // Shadows of Mirkwood
  { id:'hfg',  name:'The Hunt for Gollum',              cycle:'Shadows of Mirkwood',           diff:3.4 },
  { id:'catc', name:'Conflict at the Carrock',          cycle:'Shadows of Mirkwood',           diff:4.4 },
  { id:'ajtr', name:'A Journey to Rhosgobel',           cycle:'Shadows of Mirkwood',           diff:4.8 },
  { id:'hhem', name:'The Hills of Emyn Muil',           cycle:'Shadows of Mirkwood',           diff:2.7 },
  { id:'tdm',  name:'The Dead Marshes',                 cycle:'Shadows of Mirkwood',           diff:5.1 },
  { id:'rtm',  name:'Return to Mirkwood',               cycle:'Shadows of Mirkwood',           diff:7.2 },
  // Khazad-dûm + Dwarrowdelf
  { id:'itp',  name:'Into the Pit',                     cycle:'Khazad-dûm & Dwarrowdelf',      diff:5.3 },
  { id:'tsl',  name:'The Seventh Level',                cycle:'Khazad-dûm & Dwarrowdelf',      diff:5.5 },
  { id:'ffm',  name:'Flight from Moria',                cycle:'Khazad-dûm & Dwarrowdelf',      diff:7.5 },
  { id:'trg',  name:'The Redhorn Gate',                 cycle:'Khazad-dûm & Dwarrowdelf',      diff:5.0 },
  { id:'r2r',  name:'Road to Rivendell',                cycle:'Khazad-dûm & Dwarrowdelf',      diff:2.5 },
  { id:'twitw',name:'The Watcher in the Water',         cycle:'Khazad-dûm & Dwarrowdelf',      diff:5.5 },
  { id:'tld',  name:'The Long Dark',                    cycle:'Khazad-dûm & Dwarrowdelf',      diff:5.3 },
  { id:'fos',  name:'Foundations of Stone',             cycle:'Khazad-dûm & Dwarrowdelf',      diff:5.2 },
  { id:'saf',  name:'Shadow and Flame',                 cycle:'Khazad-dûm & Dwarrowdelf',      diff:7.5 },
  // Against the Shadow
  { id:'pip',  name:'Peril in Pelargir',                cycle:'Heirs of Númenor & Against the Shadow', diff:5.3 },
  { id:'inti', name:'Into Ithilien',                    cycle:'Heirs of Númenor & Against the Shadow', diff:6.1 },
  { id:'tsoca',name:'The Siege of Cair Andros',         cycle:'Heirs of Númenor & Against the Shadow', diff:7.2 },
  { id:'tsf',  name:"The Steward's Fear",               cycle:'Heirs of Númenor & Against the Shadow', diff:5.2 },
  { id:'tdf',  name:'The Drúadan Forest',               cycle:'Heirs of Númenor & Against the Shadow', diff:5.6 },
  { id:'eaad', name:'Encounter at Amon Dîn',            cycle:'Heirs of Númenor & Against the Shadow', diff:6.0 },
  { id:'aoo',  name:'Assault on Osgiliath',             cycle:'Heirs of Númenor & Against the Shadow', diff:6.8 },
  { id:'tbog', name:'The Blood of Gondor',              cycle:'Heirs of Númenor & Against the Shadow', diff:5.2 },
  { id:'tmv',  name:'The Morgul Vale',                  cycle:'Heirs of Númenor & Against the Shadow', diff:7.4 },
  // Ring-maker
  { id:'tfoi', name:'The Fords of Isen',                cycle:'Voice of Isengard & Ring-maker', diff:5.4 },
  { id:'tcao', name:'To Catch an Orc',                  cycle:'Voice of Isengard & Ring-maker', diff:4.2 },
  { id:'if',   name:'Into Fangorn',                     cycle:'Voice of Isengard & Ring-maker', diff:4.1 },
  { id:'tdt',  name:'The Dunland Trap',                 cycle:'Voice of Isengard & Ring-maker', diff:5.5 },
  { id:'ttt',  name:'The Three Trials',                 cycle:'Voice of Isengard & Ring-maker', diff:4.5 },
  { id:'tint', name:'Trouble in Tharbad',               cycle:'Voice of Isengard & Ring-maker', diff:5.6 },
  { id:'tnie', name:'The Nîn-in-Eilph',                 cycle:'Voice of Isengard & Ring-maker', diff:4.4 },
  { id:'cs',   name:"Celebrimbor's Secret",             cycle:'Voice of Isengard & Ring-maker', diff:4.7 },
  { id:'tac',  name:'The Antlered Crown',               cycle:'Voice of Isengard & Ring-maker', diff:7.5 },
  // Angmar Awakened
  { id:'iic',  name:'Intruders in Chetwood',            cycle:'Angmar Awakened',               diff:5.7 },
  { id:'twh',  name:'The Weather Hills',                cycle:'Angmar Awakened',               diff:6.3 },
  { id:'dd',   name:"Deadmen's Dike",                   cycle:'Angmar Awakened',               diff:7.7 },
  { id:'twoe', name:'The Wastes of Eriador',            cycle:'Angmar Awakened',               diff:7.2 },
  { id:'efmg', name:'Escape from Mount Gram',           cycle:'Angmar Awakened',               diff:3.5 },
  { id:'ate',  name:'Across the Ettenmoors',            cycle:'Angmar Awakened',               diff:4.4 },
  { id:'ttor', name:'The Treachery of Rhudaur',         cycle:'Angmar Awakened',               diff:6.1 },
  { id:'tboc', name:'The Battle of Carn Dûm',           cycle:'Angmar Awakened',               diff:9.6 },
  { id:'tdr',  name:'The Dread Realm',                  cycle:'Angmar Awakened',               diff:8.1 },
  // Dream-chaser
  { id:'vab',  name:'Voyage Across Belegaer',           cycle:'Dream-chaser',                  diff:4.8 },
  { id:'tfon', name:'The Fate of Númenor',              cycle:'Dream-chaser',                  diff:4.2 },
  { id:'rotgh',name:'Raid on the Grey Havens',          cycle:'Dream-chaser',                  diff:7.6 },
  { id:'fots', name:'Flight of the Stormcaller',        cycle:'Dream-chaser',                  diff:6.1 },
  { id:'ttitd',name:'The Thing in the Depths',          cycle:'Dream-chaser',                  diff:5.4 },
  { id:'totd', name:'Temple of the Deceived',           cycle:'Dream-chaser',                  diff:4.1 },
  { id:'tdrn', name:'The Drowned Ruins',                cycle:'Dream-chaser',                  diff:4.9 },
  { id:'ascoh',name:'A Storm on Cobas Haven',           cycle:'Dream-chaser',                  diff:7.8 },
  { id:'tcoc', name:'The City of Corsairs',             cycle:'Dream-chaser',                  diff:7.2 },
  // Haradrim
  { id:'efu',  name:'Escape from Umbar',                cycle:'Haradrim',                      diff:5.7 },
  { id:'dc',   name:'Desert Crossing',                  cycle:'Haradrim',                      diff:5.7 },
  { id:'tlaom',name:'The Long Arm of Mordor',           cycle:'Haradrim',                      diff:6.8 },
  { id:'tmum', name:'The Mûmakil',                      cycle:'Haradrim',                      diff:5.4 },
  { id:'rah',  name:'Race Across Harad',                cycle:'Haradrim',                      diff:5.2 },
  { id:'bts',  name:'Beneath the Sands',                cycle:'Haradrim',                      diff:5.5 },
  { id:'tbs',  name:'The Black Serpent',                cycle:'Haradrim',                      diff:6.4 },
  { id:'tdocg',name:'The Dungeons of Cirith Gurat',     cycle:'Haradrim',                      diff:5.8 },
  { id:'tcop', name:'The Crossings of Poros',           cycle:'Haradrim',                      diff:7.5 },
  // Ered Mithrin
  { id:'juta', name:'Journey Up the Anduin',            cycle:'Ered Mithrin',                  diff:6.0 },
  { id:'lim',  name:'Lost in Mirkwood',                 cycle:'Ered Mithrin',                  diff:5.4 },
  { id:'tkq',  name:"The King's Quest",                 cycle:'Ered Mithrin',                  diff:6.9 },
  { id:'tweh', name:'The Withered Heath',               cycle:'Ered Mithrin',                  diff:6.6 },
  { id:'rar',  name:'Roam Across Rhovanion',            cycle:'Ered Mithrin',                  diff:6.0 },
  { id:'fitn', name:'Fire in the Night',                cycle:'Ered Mithrin',                  diff:8.1 },
  { id:'tgof', name:'The Ghost of Framsburg',           cycle:'Ered Mithrin',                  diff:5.6 },
  { id:'mg',   name:'Mount Gundabad',                   cycle:'Ered Mithrin',                  diff:7.8 },
  { id:'tfowd',name:'The Fate of Wilderland',           cycle:'Ered Mithrin',                  diff:5.5 },
  // Vengeance of Mordor
  { id:'trr',  name:'The River Running',                cycle:'Vengeance of Mordor',           diff:5.0 },
  { id:'did',  name:'Danger in Dorwinion',              cycle:'Vengeance of Mordor',           diff:5.6 },
  { id:'tod',  name:'Temple of Doom',                   cycle:'Vengeance of Mordor',           diff:5.8 },
  { id:'war',  name:'Wrath and Ruin',                   cycle:'Vengeance of Mordor',           diff:6.5 },
  { id:'tcou', name:'The City of Ulfast',               cycle:'Vengeance of Mordor',           diff:6.2 },
  { id:'cotw', name:'Challenge of the Wainriders',      cycle:'Vengeance of Mordor',           diff:7.1 },
  { id:'utam', name:'Under the Ash Mountains',          cycle:'Vengeance of Mordor',           diff:6.5 },
  { id:'tlos', name:'The Land of Sorrow',               cycle:'Vengeance of Mordor',           diff:7.4 },
  { id:'tfonm',name:'The Fortress of Nurn',             cycle:'Vengeance of Mordor',           diff:8.2 },
  // Hobbit Saga
  { id:'wmw',  name:'We Must Away, Ere Break of Day',   cycle:'The Hobbit Saga',               diff:4.5 },
  { id:'otmmg',name:'Over the Misty Mountains Grim',    cycle:'The Hobbit Saga',               diff:5.3 },
  { id:'ddaco',name:'Dungeons Deep and Caverns Old',    cycle:'The Hobbit Saga',               diff:5.1 },
  { id:'fas',  name:'Flies and Spiders',                cycle:'The Hobbit Saga',               diff:4.8 },
  { id:'tlm',  name:'The Lonely Mountain',              cycle:'The Hobbit Saga',               diff:6.5 },
  { id:'tbofa',name:'The Battle of Five Armies',        cycle:'The Hobbit Saga',               diff:7.8 },
  // Lord of the Rings Saga
  { id:'asotp',name:'A Shadow of the Past',             cycle:'Lord of the Rings Saga',        diff:6.3 },
  { id:'akitd',name:'A Knife in the Dark',              cycle:'Lord of the Rings Saga',        diff:6.7 },
  { id:'fttf', name:'Flight to the Ford',               cycle:'Lord of the Rings Saga',        diff:5.6 },
  { id:'trgs', name:'The Ring Goes South',              cycle:'Lord of the Rings Saga',        diff:6.0 },
  { id:'jitd', name:'Journey in the Dark',              cycle:'Lord of the Rings Saga',        diff:7.9 },
  { id:'botf', name:'Breaking of the Fellowship',       cycle:'Lord of the Rings Saga',        diff:7.0 },
  { id:'tuh',  name:'The Uruk-hai',                     cycle:'Lord of the Rings Saga',        diff:6.0 },
  { id:'hd',   name:"Helm's Deep",                      cycle:'Lord of the Rings Saga',        diff:8.2 },
  { id:'trti', name:'The Road to Isengard',             cycle:'Lord of the Rings Saga',        diff:6.9 },
  { id:'tpotm',name:'The Passage of the Marshes',       cycle:'Lord of the Rings Saga',        diff:6.2 },
  { id:'jttcr',name:'Journey to the Cross-roads',       cycle:'Lord of the Rings Saga',        diff:7.9 },
  { id:'sl',   name:"Shelob's Lair",                    cycle:'Lord of the Rings Saga',        diff:7.3 },
  { id:'tpotg',name:'The Passing of the Grey Company',  cycle:'Lord of the Rings Saga',        diff:6.5 },
  { id:'tsog', name:'The Siege of Gondor',              cycle:'Lord of the Rings Saga',        diff:6.7 },
  { id:'tbotf',name:'The Battle of the Pelennor Fields',cycle:'Lord of the Rings Saga',        diff:7.9 },
  { id:'ttocu',name:'The Tower of Cirith Ungol',        cycle:'Lord of the Rings Saga',        diff:6.7 },
  { id:'tbgo', name:'The Black Gate Opens',             cycle:'Lord of the Rings Saga',        diff:8.8 },
  { id:'moodm',name:'Mount Doom',                       cycle:'Lord of the Rings Saga',        diff:9.3 },
  // ALeP — Oaths of the Rohirrim
  { id:'aae',  name:'Ambush at Erelas',                 cycle:'ALeP — Oaths of the Rohirrim',  diff:5.5 },
  { id:'bftb', name:'Battle for the Beacon',            cycle:'ALeP — Oaths of the Rohirrim',  diff:5.8 },
  { id:'hli',  name:"Horse Lord's Ire",                 cycle:'ALeP — Oaths of the Rohirrim',  diff:6.5 },
  { id:'tap',  name:'The Aldburg Plot',                 cycle:'ALeP — Oaths of the Rohirrim',  diff:5.4 },
  { id:'fote', name:'Fire on the Eastemnet',            cycle:'ALeP — Oaths of the Rohirrim',  diff:5.8 },
  { id:'tgor', name:'The Gap of Rohan',                 cycle:'ALeP — Oaths of the Rohirrim',  diff:6.1 },
  { id:'tgc',  name:'The Glittering Caves',             cycle:'ALeP — Oaths of the Rohirrim',  diff:6.3 },
  { id:'motr', name:'Mustering of the Rohirrim',        cycle:'ALeP — Oaths of the Rohirrim',  diff:6.0 },
  { id:'biti', name:'Blood in the Isen',                cycle:'ALeP — Oaths of the Rohirrim',  diff:7.5 },
  // ALeP — Fell Summer
  { id:'pftp', name:'Pies for the Party',               cycle:"ALeP — The Shire's Reckoning",  diff:3.5 },
  { id:'sodts',name:'Sundown on the Shire',             cycle:"ALeP — The Shire's Reckoning",  diff:4.2 },
  { id:'sotof',name:'Secrets of the Old Forest',        cycle:"ALeP — The Shire's Reckoning",  diff:5.1 },
  { id:'snitb',name:'Strange News in Bree',             cycle:'ALeP — Fell Summer',             diff:5.0 },
  { id:'fitd', name:'Fangs in the Dark',                cycle:'ALeP — Fell Summer',             diff:5.5 },
  { id:'tbpr', name:'The Brandywine Pursuit',           cycle:'ALeP — Fell Summer',             diff:5.3 },
  // ALeP — Standalones
  { id:'sots', name:'The Scouring of the Shire',        cycle:'ALeP — Standalones',             diff:6.0 },
  { id:'tnaa', name:'The Nine Are Abroad',              cycle:'ALeP — Standalones',             diff:9.0 },
  { id:'tsoe', name:'The Siege of Erebor',              cycle:'ALeP — Standalones',             diff:7.0 },
  { id:'tmog', name:'The Mirror of Galadriel',          cycle:'ALeP — Standalones',             diff:5.0 },
]

export const QUEST_MAP = Object.fromEntries(ALL_QUESTS.map(q => [q.id, q]))

export const CYCLES = [...new Set(ALL_QUESTS.map(q => q.cycle))]

// ── TALE OF YEARS QUEST ORDER (confirmed from rulebook, with XP values) ──────
// type: 'quest' | 'pause' | 'reset'
// xpFlat: flat XP per player from quest Resolution (base is always +1/10VP earned)
export const TOY_QUESTS = [
  // ── MIRKWOOD PATHS ──────────────────────────────────────────────────────────
  { type:'pause', text:'Campaign Start · Each player receives 2 XP · Add Nazgûl burden + Istari boon + Treacherous Ever Distrustful to Campaign Pool · Add 1–2 random non-enemy burdens' },
  { type:'quest', id:'ptm',  xpFlat:0 },
  { type:'quest', id:'oath', xpFlat:0, campaignOnly:true },
  { type:'quest', id:'jata', xpFlat:0 },
  { type:'quest', id:'cnd',  xpFlat:0, campaignOnly:true },
  { type:'quest', id:'efdg', xpFlat:0 },
  { type:'pause', text:'Narrative Pause — End of Mirkwood Paths · Heal 1 damage on each hero · Choose Haven · Random Presence from: Barad-Dûr, Dol Guldur, Mount Gundabad' },
  { type:'quest', id:'hfg',  xpFlat:0 },
  { type:'quest', id:'catc', xpFlat:1, note:"May add Grimbeorn the Old to Campaign Pool" },
  { type:'quest', id:'ajtr', xpFlat:2, note:"May add Wilyador to Campaign Pool" },
  { type:'pause', text:'Narrative Pause — Rhosgobel · Heal 1 damage · Lower Radagast boon cost by 1' },
  { type:'quest', id:'tdm',  xpFlat:0 },
  { type:'quest', id:'rtm',  xpFlat:2, note:"Remove Grimbeorn and Wilyador from Campaign Pool" },
  // ── AGAINST THE SHADOW ───────────────────────────────────────────────────────
  { type:'pause', text:'Narrative Pause — Against the Shadow begins · Heal 1 damage · Choose Haven · Random Presence from: Barad-Dûr, Umbar, Minas Morgul' },
  { type:'quest', id:'hhem', xpFlat:0 },
  { type:'pause', text:'Narrative Pause — Pelargir · Heal 1 damage' },
  { type:'quest', id:'pip',  xpFlat:3, note:"Remove Derufin from Campaign Pool" },
  { type:'quest', id:'inti', xpFlat:5, note:"May add Celador + Ithilien Guardians to Campaign Pool" },
  { type:'quest', id:'tsoca',xpFlat:4 },
  { type:'pause', text:'Narrative Pause — Minas Tirith · Heal 1 damage' },
  { type:'quest', id:'tsf',  xpFlat:2, note:"May add Secret Map to Campaign Pool if in victory display" },
  { type:'quest', id:'tdf',  xpFlat:2 },
  { type:'quest', id:'eaad', xpFlat:0 },
  { type:'quest', id:'aoo',  xpFlat:1 },
  { type:'quest', id:'tbog', xpFlat:2, note:"Remove Celador + Guardians + Rangers from Campaign Pool" },
  { type:'quest', id:'tmv',  xpFlat:4, note:"Remove Secret Map from Campaign Pool" },
  // ── THE RING-MAKER ──────────────────────────────────────────────────────────
  { type:'pause', text:'Narrative Pause — Ring-maker begins · Heal 1 damage · Choose Haven · Random Presence from: Barad-Dûr, Orthanc' },
  { type:'quest', id:'tfoi', xpFlat:2, note:"Add Gríma to Campaign Pool. Cannot play Gríma as hero." },
  { type:'pause', text:'Narrative Pause — Orthanc · Heal 1 damage · Lower Saruman boon cost by 1' },
  { type:'quest', id:'if',   xpFlat:0 },
  { type:'quest', id:'tdt',  xpFlat:4 },
  { type:'quest', id:'ttt',  xpFlat:1 },
  { type:'quest', id:'tint', xpFlat:0, note:"Nalir damage persists to next quest" },
  { type:'quest', id:'tcao', xpFlat:0 },
  { type:'quest', id:'tnie', xpFlat:0 },
  { type:'quest', id:'cs',   xpFlat:2 },
  { type:'quest', id:'tac',  xpFlat:3, note:"Remove Gríma from Campaign Pool" },
  // ── ANGMAR AWAKENED ─────────────────────────────────────────────────────────
  { type:'pause', text:'Narrative Pause — Angmar Awakened begins · Heal 1 damage · Lower Wise Councils boon cost by 1 · Choose Haven · Random Presence from: Barad-Dûr, Carn Dûm, Mount Gundabad' },
  { type:'quest', id:'twh',  xpFlat:0 },
  { type:'quest', id:'dd',   xpFlat:2 },
  { type:'quest', id:'twoe', xpFlat:2, note:"Amarthiúl damage persists to Across the Ettenmoors" },
  { type:'quest', id:'efmg', xpFlat:0 },
  { type:'quest', id:'ate',  xpFlat:0, note:"Amarthiúl damage persists" },
  { type:'quest', id:'ttor', xpFlat:1 },
  { type:'quest', id:'tboc', xpFlat:4 },
  { type:'quest', id:'tdr',  xpFlat:0 },
  { type:'pause', text:'Narrative Pause — Annúminas · Heal 1 damage' },
  { type:'quest', id:'iic',  xpFlat:3, note:"May add Dúnedain of Annúminas to Campaign Pool" },
  // ── DREAM-CHASER ────────────────────────────────────────────────────────────
  { type:'pause', text:'Narrative Pause — Dream-chaser begins · Heal 1 damage · Choose Haven · Random Presence from: Barad-Dûr, Umbar' },
  { type:'quest', id:'vab',  xpFlat:2 },
  { type:'quest', id:'rotgh',xpFlat:3 },
  { type:'pause', text:'Narrative Pause — Grey Havens · Heal 1 damage' },
  { type:'quest', id:'fots', xpFlat:3 },
  { type:'quest', id:'ttitd',xpFlat:1 },
  { type:'quest', id:'totd', xpFlat:0 },
  { type:'quest', id:'tdrn', xpFlat:0 },
  { type:'quest', id:'ascoh',xpFlat:1 },
  { type:'quest', id:'tfon', xpFlat:1 },
  { type:'quest', id:'tcoc', xpFlat:0 },
  // ── HARADRIM ────────────────────────────────────────────────────────────────
  { type:'pause', text:"Narrative Pause — Haradrim begins · Heal 1 damage · Choose Haven · Random Presence from: Barad-Dûr, Minas Morgul, Umbar" },
  { type:'quest', id:'efu',  xpFlat:1 },
  { type:'quest', id:'dc',   xpFlat:1 },
  { type:'quest', id:'tlaom',xpFlat:2 },
  { type:'pause', text:"Narrative Pause — Khaliel's Village · Heal 1 damage · Khaliel, Jubayr, Firyal, Yazan now available" },
  { type:'quest', id:'tmum', xpFlat:0 },
  { type:'quest', id:'rah',  xpFlat:2 },
  { type:'quest', id:'bts',  xpFlat:0 },
  { type:'quest', id:'tbs',  xpFlat:2 },
  { type:'quest', id:'tdocg',xpFlat:2, note:"May add Abaan to Campaign Pool" },
  { type:'quest', id:'tcop', xpFlat:1, note:"Remove Abaan from Campaign Pool" },
  // ── ERED MITHRIN ────────────────────────────────────────────────────────────
  { type:'pause', text:"Narrative Pause — Ered Mithrin begins · Heal 1 damage · Choose Haven · Random Presence from: Barad-Dûr, Dol Guldur, Goblin-town, Mount Gundabad" },
  { type:'quest', id:'juta', xpFlat:2, note:"Add Haldan to Campaign Pool" },
  { type:'pause', text:"Narrative Pause — Woodmen's Village · Heal 1 damage" },
  { type:'quest', id:'oath', xpFlat:0, campaignOnly:true, note:"Ered Mithrin placement of The Oath" },
  { type:'quest', id:'cnd',  xpFlat:2, campaignOnly:true, note:"Ered Mithrin placement of Caves of Nibin-Dûm" },
  { type:'quest', id:'lim',  xpFlat:0, note:"Remove Haldan from Campaign Pool" },
  { type:'pause', text:"Narrative Pause — Dale · Heal 1 damage" },
  { type:'quest', id:'tkq',  xpFlat:3 },
  { type:'quest', id:'tweh', xpFlat:3 },
  { type:'quest', id:'rar',  xpFlat:2 },
  { type:'quest', id:'fitn', xpFlat:0 },
  { type:'pause', text:"Narrative Pause — Hrogar's Hill · Heal 1 damage" },
  { type:'quest', id:'tgof', xpFlat:1, note:"May purchase Scatha's Teeth as Permanent Boon" },
  { type:'quest', id:'mg',   xpFlat:2, note:"May purchase Reforged Wormsbane as Permanent Boon" },
  { type:'quest', id:'tfowd',xpFlat:1 },
  // ── VENGEANCE OF MORDOR ─────────────────────────────────────────────────────
  { type:'pause', text:"Narrative Pause — Vengeance of Mordor begins · Heal 1 damage · Choose Haven · Random Presence from: Barad-Dûr, Umbar" },
  { type:'quest', id:'trr',  xpFlat:2 },
  { type:'pause', text:"Narrative Pause — Dorwinion's Capital · Heal 1 damage" },
  { type:'quest', id:'did',  xpFlat:0 },
  { type:'pause', text:"Narrative Pause — Dorwinion's Capital · Heal 1 damage" },
  { type:'quest', id:'tod',  xpFlat:0 },
  { type:'quest', id:'war',  xpFlat:1 },
  { type:'quest', id:'tcou', xpFlat:1 },
  { type:'quest', id:'cotw', xpFlat:2 },
  { type:'quest', id:'utam', xpFlat:2 },
  { type:'quest', id:'tlos', xpFlat:3 },
  { type:'quest', id:'tfonm',xpFlat:1 },
  // ── THE HOBBIT SAGA ─────────────────────────────────────────────────────────
  { type:'pause', text:"Hobbit Saga: Treasures found during these quests go into the Campaign Pool. After the Hobbit Saga, treasures are shuffled into the owning player's deck." },
  { type:'quest', id:'wmw',  xpFlat:0 },
  { type:'quest', id:'otmmg',xpFlat:0 },
  { type:'quest', id:'ddaco',xpFlat:0 },
  { type:'quest', id:'fas',  xpFlat:0 },
  { type:'quest', id:'tlm',  xpFlat:0 },
  { type:'quest', id:'tbofa',xpFlat:0 },
  // ── SAGA RESET ──────────────────────────────────────────────────────────────
  { type:'reset', text:'⚠ SAGA RESET — Official Saga campaign rules now apply. Reset ALL variables: damage cleared, threat penalties cancelled, Dead Pile cleared, Boons and Burdens removed. Cannot use Sméagol, Saruman or Gríma from this point.' },
  // ── LORD OF THE RINGS SAGA ──────────────────────────────────────────────────
  { type:'quest', id:'asotp',xpFlat:0 },
  { type:'quest', id:'akitd',xpFlat:0 },
  { type:'quest', id:'fttf', xpFlat:0 },
  { type:'quest', id:'trgs', xpFlat:0 },
  { type:'quest', id:'jitd', xpFlat:0 },
  { type:'quest', id:'botf', xpFlat:0 },
  { type:'quest', id:'tuh',  xpFlat:0 },
  { type:'quest', id:'hd',   xpFlat:0 },
  { type:'quest', id:'trti', xpFlat:0 },
  { type:'quest', id:'tpotm',xpFlat:0 },
  { type:'quest', id:'jttcr',xpFlat:0 },
  { type:'quest', id:'sl',   xpFlat:0 },
  { type:'quest', id:'tpotg',xpFlat:0 },
  { type:'quest', id:'tsog', xpFlat:0 },
  { type:'quest', id:'tbotf',xpFlat:0 },
  { type:'quest', id:'ttocu',xpFlat:0 },
  { type:'quest', id:'tbgo', xpFlat:0 },
  { type:'quest', id:'moodm',xpFlat:0 },
]

// ── OFFICIAL CAMPAIGNS ────────────────────────────────────────────────────────
export const CAMPAIGNS = [
  {
    id: 'mirkwood',
    name: 'Mirkwood Paths',
    icon: '🌲',
    desc: 'Core Set + Dark of Mirkwood · 5 quests',
    quests: ['ptm','oath','jata','cnd','efdg'],
  },
  {
    id: 'angmar',
    name: 'Angmar Awakened',
    icon: '💀',
    desc: 'Campaign Expansion · 9 quests',
    quests: ['iic','twh','dd','twoe','efmg','ate','ttor','tboc','tdr'],
  },
  {
    id: 'dream',
    name: 'Dream-chaser',
    icon: '⛵',
    desc: 'Campaign Expansion · 9 quests · Sailing mechanic',
    quests: ['vab','tfon','rotgh','fots','ttitd','totd','tdrn','ascoh','tcoc'],
  },
  {
    id: 'ered',
    name: 'Ered Mithrin',
    icon: '🐉',
    desc: 'Campaign Expansion · 9 quests · Dragon threat',
    quests: ['juta','lim','tkq','tweh','rar','fitn','tgof','mg','tfowd'],
  },
  {
    id: 'fotr',
    name: 'Fellowship of the Ring',
    icon: '💍',
    desc: 'Saga Expansion · 6 quests',
    quests: ['asotp','akitd','fttf','trgs','jitd','botf'],
  },
  {
    id: 'tt',
    name: 'The Two Towers',
    icon: '⚔️',
    desc: 'Saga Expansion · 6 quests',
    quests: ['tuh','hd','trti','tpotm','jttcr','sl'],
  },
  {
    id: 'rotk',
    name: 'Return of the King',
    icon: '👑',
    desc: 'Saga Expansion · 6 quests',
    quests: ['tpotg','tsog','tbotf','ttocu','tbgo','moodm'],
  },
  {
    id: 'alep-oaths',
    name: 'ALeP — Oaths of the Rohirrim',
    icon: '🧡',
    desc: 'ALeP Fan Campaign · 9 quests',
    quests: ['aae','bftb','hli','tap','fote','tgor','tgc','motr','biti'],
  },
]

// ── DEFAULT TOY STATE ─────────────────────────────────────────────────────────
export const DEFAULT_TOY = {
  heroes: [
    { id:'h1', name:'Hero 1', sphere:'Leadership', maxHp:5, threatCost:10, penalty:0, damage:0, conditions:[], boons:[] },
    { id:'h2', name:'Hero 2', sphere:'Tactics',    maxHp:4, threatCost:11, penalty:0, damage:0, conditions:[], boons:[] },
    { id:'h3', name:'Hero 3', sphere:'Spirit',     maxHp:3, threatCost:8,  penalty:0, damage:0, conditions:[], boons:[] },
  ],
  xpPool: 2,
  deadPile: [],
  boons: [],
  burdens: [
    { id:'b1', name:'Nazgûl Burden (random)', addedAt:'Campaign Start' },
    { id:'b2', name:'Treacherous Ever Distrustful', addedAt:'Campaign Start' },
  ],
  haven: 'Hobbiton',
  presence: 'Dol Guldur',
  questResults: {},
  xpLog: [],
  narrativePauses: 0,
  startDate: new Date().toISOString().split('T')[0],
}

// ── HELPERS ───────────────────────────────────────────────────────────────────
export function diffClass(d) {
  if (d < 5)   return 'diff-easy'
  if (d < 7)   return 'diff-med'
  if (d < 8.5) return 'diff-hard'
  return 'diff-brutal'
}

export function uid() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2)
}

export function formatDate(s) {
  if (!s) return ''
  return new Date(s).toLocaleDateString('en-AU', { day:'2-digit', month:'short', year:'2-digit' })
}
